name: Tests

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12.8.4
        uses: actions/setup-node@v1
        with: 
          node-version: '12.8.4'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: yarn run test
